### PR TITLE
kakshay21 unittest2

### PR DESCRIPTION
**Pull request by kakshay21**
https://github.com/plone/Products.CMFPlone/issues/1882

### CODE REVIEW

**Comment by kakshay21** [comment]
sorry, How can I undo this?

**Comment by prakharjoshi** [comment]
@kakshay21  create another PR with the revert changes and first that needs to be merged and then create new PR with your changes again

**Comment by kakshay21** [comment]
in the same branch from which i made changes, right? 
@prakharjoshi

**Comment by prakharjoshi** [comment]
Its better you create a separate branch for revert changes. And then later you can create another PR with this branch later one the revert changes are merged

**Comment by prakharjoshi** [comment]
@gforcada We should keep Pre checks for merging PRs. Like it can be merged only if the tests passes and for Core plone projects it should be approved by atleast by one. Ideas ?

**Comment by gforcada** [comment]
@prakharjoshi yes that would be nice, on the other hand if contributors never *screw up*, they will never learn how to revert a pull request 😆 

Jokes aside, yes, the main problem is that there are so many repositories that clicking on all of them is cumbersome and scripting it... well I would rather do something else 😄 

As long as contributors behave there is no problem of one or two pull requests every now and then being merged while they should not, as long as we notice 😓

**Pull request merged**
