### PR TITLE
Make formatting of start & end dates consistent with other dates

### PR DESCRIPTION
**Pull request by djowett**
in tabular view

### CODE REVIEW

**Comment by djowett** [comment]
duplicate of #21

**Comment by djowett** [comment]
#21 seems to be going nowhere, so I'm reopening this.  I figured out this fix before finding that issue (in case that matters)

**Comment by jensens** [comment]
http://jenkins.plone.org/job/pull-request-4.3/95/

**Comment by jensens** [comment]
tests are green 

@djowett please add a line to the changelog, then we can merge

**Comment by djowett** [comment]
@jensens done. Thanks!

**Comment by djowett** [comment]
@jensens Any chance of a release with this in?

**Comment by jensens** [comment]
ping the release team @mauritsvanrees @esteele who else?

**Comment by mauritsvanrees** [comment]
Done. 1.0.14 released. Thanks for your work.

**Comment by djowett** [comment]
thanks @mauritsvanrees (and @jensens)

**Pull request merged**
