### PR TITLE
reverting changes

### PR DESCRIPTION
**Pull request by kakshay21**

### CODE REVIEW

**Comment by kakshay21** [comment]
@gforcada I'm having little trouble in resolving conflicting file

**Comment by gforcada** [comment]
@kakshay21 let me have a look

**Comment by gforcada** [comment]
Oh I see, you started from an old commit, rather than from master, that's why you have the CHANGES.rst conflict.

First thing: whenever you start working on a repository, **always** do ``git checkout master && git fetch && git rebase``. This will make sure that you are on the latest commit. Then create the branch and start working on your improvement/fixes, etc etc.

**Comment by kakshay21** [comment]
thank you @gforcada 
I'll keep in mind

**Comment by gforcada** [comment]
Everything reverted, no puppies where harmed nor any animal got injured 😆 

@kakshay21 if you are online, let's talk on IRC: https://plone.org/support/chat

**Pull request merged**
