### PR TITLE
Update tabular_view.pt

### PR DESCRIPTION
**Pull request by kitesurfer1404**
Added localized time for Event start- and end-date.

### CODE REVIEW

**Comment by djowett** [comment]
Just to be clear, without this PR the formatting of start & end dates are *inconsistent* with that of other dates like ModificationDate

**Comment by jensens** [comment]
http://jenkins.plone.org/job/pull-request-5.0/144/

**Comment by jensens** [comment]
change log entry is missing

**Comment by jensens** [comment]
@kitesurfer1404 you are not listed as Plone Contributor, so we can not merge this PR. It would be great if you sign the contributor agreement and become a Plone core contributor. For more information see https://plone.org/foundation/contributors-agreement

**Comment by jensens** [comment]
I close this one, since there was no response. Please reopen in case someone plans to work on this.

**Pull request closed without merging**
